DROP TABLE CUSTOMER
CREATE TABLE CUSTOMER (
  ID NUMBER(11) NOT NULL,
  FIRST_NAME VARCHAR(45) DEFAULT NULL,
  LAST_NAME VARCHAR(45) DEFAULT NULL,
  EMAIL VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ID)
)

    DELETE  FROM CUSTOMER;
    INSERT INTO CUSTOMER VALUES (1,'DAVID','ADAMS','DAVID@DEMO.COM');
	  INSERT INTO CUSTOMER VALUES (2,'JOHN','DOE','JOHN@DEMO.COM');  
    INSERT INTO CUSTOMER VALUES	(3,'AJAY','RAO','AJAY@DEMO.COM');
    INSERT INTO CUSTOMER VALUES	(4,'MARY','PUBLIC','MARY@DEMO.COM');
    INSERT INTO CUSTOMER VALUES	(5,'MAXWELL','DIXON','MAX@DEMO.COM'); 
    COMMIT;
SELECT * FROM CUSTOMER;
    
DROP SEQUENCE CUSTOMER_ID_SEQ;
CREATE SEQUENCE CUSTOMER_ID_SEQ;
 
SELECT CUSTOMER_ID_SEQ.NEXTVAL FROM DUAL;